/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilanloginn;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;


/**
 *
 * @author Fahri
 */
public class dataproduk extends javax.swing.JPanel {

    /**
     * Creates new form dataproduk
     */
    public dataproduk() {
        initComponents();
        viewDataProduk("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        panel_dataproduk = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        btn_hps = new javax.swing.JButton();
        btn_tmbh1 = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panel_tambahh = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbkat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsupplier = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthb = new javax.swing.JTextField();
        panel_editt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_batal1 = new javax.swing.JButton();
        btn_simpan1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtstok1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbkat1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtnama1 = new javax.swing.JTextField();
        txtid1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtsupplier1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txthj1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txthb1 = new javax.swing.JTextField();
        btncekid = new javax.swing.JButton();
        btnceknama = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panel_utama.setLayout(new java.awt.CardLayout());

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_produk", "no", "nama produk", "stok", "supplier", "kategori", "harga beli", "harga jual"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);
        if (tabeldata.getColumnModel().getColumnCount() > 0) {
            tabeldata.getColumnModel().getColumn(7).setResizable(false);
        }

        btn_hps.setText("Hapus");
        btn_hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hpsActionPerformed(evt);
            }
        });

        btn_tmbh1.setText("Tambah");
        btn_tmbh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbh1ActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setText("DATA PRODUK");

        txt_cari.setText("Cari");
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-24.png"))); // NOI18N

        javax.swing.GroupLayout panel_dataprodukLayout = new javax.swing.GroupLayout(panel_dataproduk);
        panel_dataproduk.setLayout(panel_dataprodukLayout);
        panel_dataprodukLayout.setHorizontalGroup(
            panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataprodukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dataprodukLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_dataprodukLayout.createSequentialGroup()
                        .addComponent(btn_tmbh1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hps, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(183, 183, 183)
                        .addComponent(txt_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addComponent(jScrollPane1)))
        );
        panel_dataprodukLayout.setVerticalGroup(
            panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dataprodukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txt_cari)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tmbh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );

        panel_utama.add(panel_dataproduk, "card2");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel2.setText("TAMBAH PRODUK");

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(0, 51, 255));
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("STOK");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("SUPPLIER");

        txtstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("KATEGORI");

        cmbkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Mandi", "Perawatan Pribadi", " " }));
        cmbkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("NAMA PRODUK");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("ID PRODUK");

        txtsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("HARGA BELI");

        txthj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthjActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("HARGA JUAL");

        txthb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_tambahhLayout = new javax.swing.GroupLayout(panel_tambahh);
        panel_tambahh.setLayout(panel_tambahhLayout);
        panel_tambahhLayout.setHorizontalGroup(
            panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tambahhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_tambahhLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tambahhLayout.createSequentialGroup()
                        .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_tambahhLayout.createSequentialGroup()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(601, 601, 601))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tambahhLayout.createSequentialGroup()
                        .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_tambahhLayout.createSequentialGroup()
                                .addComponent(txthb)
                                .addGap(121, 121, 121))
                            .addGroup(panel_tambahhLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panel_tambahhLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbkat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(150, 150, 150)))
                        .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthj)
                            .addGroup(panel_tambahhLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(97, 97, 97)))
                        .addGap(106, 106, 106))
                    .addGroup(panel_tambahhLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                        .addGap(216, 216, 216))
                    .addGroup(panel_tambahhLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_tambahhLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtstok, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtid)
                        .addComponent(txtnama)
                        .addGroup(panel_tambahhLayout.createSequentialGroup()
                            .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_tambahhLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(30, 30, 30)))
                            .addGap(687, 687, 687)))
                    .addContainerGap()))
        );
        panel_tambahhLayout.setVerticalGroup(
            panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tambahhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tambahhLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(cmbkat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txthb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthj))
                .addContainerGap())
            .addGroup(panel_tambahhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_tambahhLayout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtid)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtnama)
                    .addGap(46, 46, 46)
                    .addComponent(txtstok)
                    .addGap(221, 221, 221)))
        );

        panel_utama.add(panel_tambahh, "card2");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel3.setText("EDIT PRODUK");

        btn_batal1.setText("Batal");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        btn_simpan1.setBackground(new java.awt.Color(0, 51, 255));
        btn_simpan1.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan1.setText("Simpan");
        btn_simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("STOK");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("SUPPLIER");

        txtstok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstok1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("KATEGORI");

        cmbkat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Mandi", "Perawatan Pribadi", " " }));
        cmbkat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkat1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("NAMA PRODUK");

        txtnama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("ID PRODUK");

        txtsupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplier1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("HARGA BELI");

        txthj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthj1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("HARGA JUAL");

        txthb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthb1ActionPerformed(evt);
            }
        });

        btncekid.setText("CEK ID");
        btncekid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekidActionPerformed(evt);
            }
        });

        btnceknama.setText("CEK NAMA");
        btnceknama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceknamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_edittLayout = new javax.swing.GroupLayout(panel_editt);
        panel_editt.setLayout(panel_edittLayout);
        panel_edittLayout.setHorizontalGroup(
            panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_edittLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnceknama)
                    .addComponent(btncekid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
            .addGroup(panel_edittLayout.createSequentialGroup()
                .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_edittLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(panel_edittLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(panel_edittLayout.createSequentialGroup()
                                .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthb1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addGroup(panel_edittLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbkat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(121, 121, 121)
                                .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17)
                                    .addComponent(txthj1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtsupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 106, Short.MAX_VALUE))
            .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_edittLayout.createSequentialGroup()
                    .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_edittLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btn_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_edittLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtstok1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                .addComponent(txtnama1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(txtid1))))
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        panel_edittLayout.setVerticalGroup(
            panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_edittLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(111, 111, 111)
                .addComponent(btncekid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnceknama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(2, 2, 2)
                .addComponent(txtsupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbkat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthb1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthj1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_edittLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(panel_edittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(jLabel15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtstok1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );

        panel_utama.add(panel_editt, "card2");

        add(panel_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hpsActionPerformed
        // TODO add your handling code here:
        int n = tabeldata.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(tabeldata.getValueAt(n, 0).toString());

            int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin untuk menghapus data produk ini?",
                "Hapus Data",JOptionPane.YES_NO_OPTION);
            if(pilihan == 0){
                //yes
                String Q = "DELETE FROM produk WHERE id_produk="+id+" ";
                try {
                    Connection K = Config.configDB();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewDataProduk("");
                } catch (Exception e) {
                }
            }else {
                //no
            }
        }
    }//GEN-LAST:event_btn_hpsActionPerformed

    private void btn_tmbh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbh1ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();

        panel_utama.add(panel_tambahh);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_tmbh1ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();

        panel_utama.add(panel_editt);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        txt_cari.setText("");
        viewDataProduk("");
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        String key = txt_cari.getText();
        String w = "WHERE "
        + "nama_produk LIKE '%"+key+"%' "
        + "OR supplier LIKE '%"+key+"%' "
        + "OR kategori LIKE '%"+key+"%' ";
        viewDataProduk(w);
    }//GEN-LAST:event_txt_cariKeyReleased

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void cmbkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkatActionPerformed

    private void txtstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtid.getText());
        String name = txtnama.getText();
        String stok = txtstok.getText();
        String supplier = txtsupplier.getText();
        String kategori = cmbkat.getSelectedItem().toString();
        String hrgbeli = txthb.getText();
        String hrgjual = txthj.getText();

        try {
            Connection K = Config.configDB(); // Pastikan koneksi ke database berhasil

            if (K == null) {
                JOptionPane.showMessageDialog(this, "Koneksi ke database gagal.");
                return; // Hentikan eksekusi jika koneksi gagal
            }

            String Q = "INSERT INTO produk (id_produk, nama_produk, stok, supplier, kategori, harga_beli, harga_jual) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement PS = K.prepareStatement(Q);

            PS.setInt(1, id);
            PS.setString(2, name);
            PS.setString(3, stok);
            PS.setString(4, supplier);
            PS.setString(5, kategori);
            PS.setString(6, hrgbeli);
            PS.setString(7, hrgjual);

            PS.executeUpdate();

            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

            // Memanggil metode untuk memperbarui data di tabel jika sudah diimplementasikan
            viewDataProduk("");
            txtnama.requestFocus();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(panel_dataproduk);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txtsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierActionPerformed

    private void txthjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthjActionPerformed

    private void txthbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthbActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(panel_dataproduk);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void btn_simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan1ActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtid1.getText());
        String name = txtnama1.getText();
        String stok = txtstok1.getText();
        String supplier = txtsupplier1.getText();
        String kategori = cmbkat1.getSelectedItem().toString();
        String hrgbeli = txthb1.getText();
        String hrgjual = txthj1.getText();
    
    // Query SQL untuk mengupdate data
       String query = "UPDATE produk SET nama_produk=?, stok=?, supplier=?, kategori=?, harga_beli=?, harga_jual=? WHERE id_produk = ?";
    
        try {
        // Membuat koneksi dan PreparedStatement
            Connection conn = Config.configDB();
            PreparedStatement PS = conn.prepareStatement(query);

            // Mengatur nilai pada query
            PS.setString(1, name);
            PS.setString(2, stok);
            PS.setString(3, supplier);
            PS.setString(4, kategori);
            PS.setString(5, hrgbeli);
            PS.setString(6, hrgjual);
            PS.setInt(7, id);    // ID yang menjadi acuan untuk update

            // Eksekusi query
            int res = PS.executeUpdate();

            // Periksa hasil eksekusi
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
                viewDataProduk("");
                txtnama1.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal diubah!");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_simpan1ActionPerformed

    private void txtstok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstok1ActionPerformed

    private void cmbkat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkat1ActionPerformed

    private void txtnama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama1ActionPerformed

    private void txtsupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplier1ActionPerformed

    private void txthj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthj1ActionPerformed

    private void txthb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthb1ActionPerformed

    private void btncekidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekidActionPerformed
        // TODO add your handling code here:
        try {
            Connection K = Config.configDB();
            Statement S = K.createStatement();
            String Q = "Select * from produk" + " where id_produk='" + txtid1.getText() + "'";
            ResultSet R = S.executeQuery(Q);

            if (R.next()) {
                btn_simpan.setEnabled(true);
                txtnama1.setText(R.getString("nama_produk"));
                txtstok1.setText(R.getString("stok"));
                txtsupplier1.setText(R.getString("supplier"));
                cmbkat1.setSelectedItem(R.getString("kategori"));
                txthb1.setText(R.getString("harga_beli"));
                txthj1.setText(R.getString("harga_jual"));
                txtid1.setText(R.getString("id_produk"));
            } else {
                JOptionPane.showMessageDialog(this, "ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                btn_simpan.setEnabled(false);
                txtnama1.setText("");
                txtstok1.setText("");
                txtsupplier1.setText("");
                cmbkat1.setSelectedItem("");
                txthb1.setText("");
                txthj1.setText("");
                txtid1.setText("");
                txtid1.requestFocus();

            }
        }catch (Exception e) {
            System.out.println("Koneksi GAGAL" + e.toString());
        }
    }//GEN-LAST:event_btncekidActionPerformed

    private void btnceknamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceknamaActionPerformed
        // TODO add your handling code here:
        try {
            Connection K = Config.configDB();
            Statement S = K.createStatement();
            String Q = ("Select * from produk" + " where nama_produk like('%"+txtnama1.getText()+"%')");
            ResultSet R = S.executeQuery(Q);

            if (R.next()) {
                btn_simpan.setEnabled(true);
                txtnama1.setText(R.getString("nama_produk"));
                txtstok1.setText(R.getString("stok"));
                txtsupplier1.setText(R.getString("supplier"));
                cmbkat1.setSelectedItem(R.getString("kategori"));
                txthb1.setText(R.getString("harga_beli"));
                txthj1.setText(R.getString("harga_jual"));
                txtid1.setText(R.getString("id_produk"));
            } else {
                JOptionPane.showMessageDialog(this, "Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                btn_simpan.setEnabled(false);
                txtnama1.setText("");
                txtstok1.setText("");
                txtsupplier1.setText("");
                cmbkat1.setSelectedItem("");
                txthb1.setText("");
                txthj1.setText("");
                txtid1.setText("");
                txtid1.requestFocus();

            }
        }catch (Exception e) {
            System.out.println("Koneksi GAGAL" + e.toString());
        }
    }//GEN-LAST:event_btnceknamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hps;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_simpan1;
    private javax.swing.JButton btn_tmbh1;
    private javax.swing.JButton btncekid;
    private javax.swing.JButton btnceknama;
    private javax.swing.JComboBox<String> cmbkat;
    private javax.swing.JComboBox<String> cmbkat1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_dataproduk;
    private javax.swing.JPanel panel_editt;
    private javax.swing.JPanel panel_tambahh;
    private javax.swing.JPanel panel_utama;
    private static javax.swing.JTable tabeldata;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txthb;
    private javax.swing.JTextField txthb1;
    private javax.swing.JTextField txthj;
    private javax.swing.JTextField txthj1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnama1;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txtstok1;
    private javax.swing.JTextField txtsupplier;
    private javax.swing.JTextField txtsupplier1;
    // End of variables declaration//GEN-END:variables
    public static void viewDataProduk(String where) {
        try {
            DefaultTableModel m = (DefaultTableModel) tabeldata.getModel();
            m.getDataVector().removeAllElements();
            Connection K = Config.configDB();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM produk "+where;
            ResultSet R = S.executeQuery(Q);
            int n = 1;
            while (R.next()) {                 
                int id = R.getInt("id_produk");
                String nama = R.getString("nama_produk");
                String stok = R.getString("stok");
                String supplier = R.getString("supplier");
                String kategori = R.getString("kategori");
                String hrgbeli = R.getString("harga_beli");
                String hrgjual = R.getString("harga_jual");
                Object[] data = {id,n,  nama, stok, supplier, kategori, hrgbeli, hrgjual};
                m.addRow(data);
                n++;
            }
            
            tabeldata.getColumnModel().getColumn(0).setMinWidth(0);
            tabeldata.getColumnModel().getColumn(0).setMaxWidth(0);
            
        } catch (Exception e) {
            //error handling
        }
    }
}
